#!/usr/bin/env bash
# start.sh — render the quadlet unit and start the server.
set -euo pipefail
# shellcheck source=lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

require_cmd uv jq yq podman systemctl

[ -f "$CONFIG_PATH" ] || die "no config at ${CONFIG_PATH}; run 'make setup' first"

backend="$(yq -r '.gpu.backend' "$CONFIG_PATH")"
image="$(yq -r '.gpu.image' "$CONFIG_PATH")"
device_name="$(yq -r '.gpu.device_name' "$CONFIG_PATH")"
host="$(yq -r '.server.host' "$CONFIG_PATH")"
port="$(yq -r '.server.port' "$CONFIG_PATH")"
api_key="$(yq -r '.server.api_key' "$CONFIG_PATH")"
sleep_idle="$(yq -r '.server.sleep_idle_seconds' "$CONFIG_PATH")"
models_max="$(yq -r '.runtime.models_max' "$CONFIG_PATH")"

[ "$models_max" -gt 0 ] || die "no models enabled; run 'make setup'"

log_step "Checking the VRAM budget"
if ! budget="$(llmenv --config "$CONFIG_PATH" budget --models-dir "$MODELS_DIR")"; then
    echo "$budget" | jq -r '"  short by \(.shortfall_mib) MiB"'
    echo "$budget" | jq -r '.remedies[] | "    - \(.)"'
    die "VRAM budget exceeded for models_max=${models_max}; adjust the config and retry"
fi
echo "$budget" | jq -r '"  available \(.available_mib) MiB, required \(.required_mib) MiB"'

log_step "Resolving the GPU device"
device="all"
if [ "$backend" != "cpu" ] && [ -n "$device_name" ] && [ "$device_name" != "null" ]; then
    listing_file="$(mktemp)"
    podman run --rm --device /dev/dri --entrypoint /app/llama-server \
        "$image" --list-devices >"$listing_file" 2>/dev/null || true
    if resolved="$(llmenv resolve-device --device-name "$device_name" \
                   --listing-file "$listing_file")"; then
        device="$(echo "$resolved" | jq -r '.device')"
        log_info "pinned to ${device} (${device_name})"
    else
        log_warn "could not resolve ${device_name}; offloading to all devices"
    fi
    rm -f "$listing_file"
fi

log_step "Generating presets.ini"
presets_path="${HOME}/.config/llm-env/presets.ini"
llmenv --config "$CONFIG_PATH" presets \
    --models-dir /models --device "$device" --output "$presets_path" >/dev/null
log_info "wrote ${presets_path}"

log_step "Rendering the quadlet unit"
mkdir -p "$QUADLET_DIR"
device_lines="AddDevice=/dev/dri"
[ "$backend" = "rocm" ] && device_lines="${device_lines}"$'\n'"AddDevice=/dev/kfd"

cat > "${QUADLET_DIR}/${UNIT_NAME}.container" <<EOF
# Generated by start.sh from ${CONFIG_PATH}. Edits will be overwritten.
[Unit]
Description=llama.cpp router server (${backend})
After=network-online.target

[Container]
Image=${image}
ContainerName=${UNIT_NAME}
${device_lines}
Volume=${MODELS_DIR}:/models:ro,z
Volume=${presets_path}:/etc/llama/presets.ini:ro,z
PublishPort=${port}:${port}
Environment=LLAMA_ARG_MODELS_PRESET=/etc/llama/presets.ini
Environment=LLAMA_ARG_MODELS_MAX=${models_max}
Environment=LLAMA_ARG_HOST=${host}
Environment=LLAMA_ARG_PORT=${port}
Environment=LLAMA_API_KEY=${api_key}
Exec=--sleep-idle-seconds ${sleep_idle}
HealthCmd=curl -fsS http://127.0.0.1:${port}/health || exit 1
HealthInterval=10s
HealthRetries=30
HealthStartPeriod=20s

[Service]
Restart=on-failure
TimeoutStartSec=300

[Install]
WantedBy=default.target
EOF
log_info "wrote ${QUADLET_DIR}/${UNIT_NAME}.container"
chmod 600 "${QUADLET_DIR}/${UNIT_NAME}.container"

log_step "Starting the service"
systemctl --user daemon-reload
systemctl --user start "${UNIT_NAME}.service"

log_step "Waiting for health"
# Probe 127.0.0.1 explicitly: "localhost" resolves to ::1 first on this system while
# podman publishes the port on 0.0.0.0 (IPv4), so a localhost probe would never connect.
for _ in $(seq 1 60); do
    if curl -fsS -o /dev/null "http://127.0.0.1:${port}/health" 2>/dev/null; then
        log_info "server is ready"
        ip="$(ip -4 -json addr show scope global 2>/dev/null \
              | jq -r '[.[].addr_info[].local] | first // "unknown"')"
        mdns="$(yq -r '.server.mdns_name' "$CONFIG_PATH")"
        echo
        echo "  Local:   http://127.0.0.1:${port}/v1"
        echo "  Network: http://${ip}:${port}/v1"
        echo "  mDNS:    http://${mdns}.local:${port}/v1"
        echo "  API key: ${api_key}"
        echo
        echo "  Models:"
        yq -r '.models[] | select(.enabled) | "    - " + .alias' "$CONFIG_PATH"
        exit 0
    fi
    sleep 1
done

log_error "server did not become healthy within 60s"
echo "  Logs: journalctl --user -u ${UNIT_NAME}.service -n 50"
exit 1
