import configparser
import copy
import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pylib.presets import render_presets, write_presets

CFG = {
    "version": 1,
    "runtime": {
        "models_max": 2,
        "parallel_slots": 1,
        "ubatch_size": 512,
        "flash_attn": True,
        "cache_type_k": "q5_1",
        "cache_type_v": "q5_1",
    },
    "models": [
        {
            "alias": "gemma4",
            "enabled": True,
            "file": "gemma-4-12B-it-Q4_K_M.gguf",
            "ctx_size": 131072,
            "n_gpu_layers": 99,
        },
        {
            "alias": "ornith",
            "enabled": True,
            "file": "ornith-1.0-9b-Q4_K_M.gguf",
            "ctx_size": 131072,
            "n_gpu_layers": 99,
        },
    ],
}


def parse(text: str) -> configparser.ConfigParser:
    parser = configparser.ConfigParser()
    parser.read_string(text)
    return parser


def test_exact_one_slot_no_fit_preset():
    text = render_presets(CFG, "/models", "Vulkan0")
    assert text == (
        "; Generated by llm-env. Do not edit; regenerated on every start.\n"
        "[*]\n"
        "device = Vulkan0\n"
        "parallel = 1\n"
        "ubatch-size = 512\n"
        "flash-attn = on\n"
        "cache-type-k = q5_1\n"
        "cache-type-v = q5_1\n"
        "fit = off\n"
        "context-shift = off\n"
        "\n"
        "[gemma4]\n"
        "model = /models/gemma-4-12B-it-Q4_K_M.gguf\n"
        "ctx-size = 131072\n"
        "n-gpu-layers = 99\n"
        "\n"
        "[ornith]\n"
        "model = /models/ornith-1.0-9b-Q4_K_M.gguf\n"
        "ctx-size = 131072\n"
        "n-gpu-layers = 99\n"
        "\n"
    )
    assert "n-predict" not in text


def test_no_default_section_and_no_version_key():
    """llama-server registers [DEFAULT] as a phantom model, so it must not appear."""
    text = render_presets(CFG, "/models", "Vulkan0")
    assert "[DEFAULT]" not in text
    assert re.search(r"(?mi)^\s*version\s*=", text) is None
    assert parse(text).defaults() == {}


def test_version_check_tolerates_a_filename_containing_version():
    """The guard must match a version directive, not the substring anywhere."""
    cfg = {
        **CFG,
        "models": [
            {
                "alias": "verbose",
                "enabled": True,
                "file": "llama-3-70b-version2.gguf",
                "ctx_size": 4096,
                "n_gpu_layers": 99,
            }
        ],
    }
    text = render_presets(cfg, "/models", "Vulkan0")
    assert "version2.gguf" in text
    assert re.search(r"(?mi)^\s*version\s*=", text) is None
    assert parse(text).defaults() == {}


def test_output_starts_with_a_comment_header():
    text = render_presets(CFG, "/models", "Vulkan0")
    assert text.startswith("; Generated by llm-env")
    # A leading comment must not break parsing of the first real section.
    assert "*" in parse(text).sections()


def test_global_star_section_carries_shared_settings():
    parser = parse(render_presets(CFG, "/models", "Vulkan0"))
    star = parser["*"]
    assert star["device"] == "Vulkan0"
    assert star["flash-attn"] == "on"
    assert star["cache-type-k"] == "q5_1"
    assert star["cache-type-v"] == "q5_1"


def test_only_enabled_models_get_sections():
    parser = parse(render_presets(CFG, "/models", "Vulkan0"))
    sections = [s for s in parser.sections() if s != "*"]
    assert sections == ["gemma4", "ornith"]


def test_model_section_has_absolute_path_and_settings():
    parser = parse(render_presets(CFG, "/models", "Vulkan0"))
    section = parser["gemma4"]
    assert section["model"] == "/models/gemma-4-12B-it-Q4_K_M.gguf"
    assert section["ctx-size"] == "131072"
    assert section["n-gpu-layers"] == "99"


SAMPLER_KEYS = ("temp", "top-p", "top-k", "repeat-penalty")


@pytest.mark.parametrize("temperature", [1.0, 0.0])
def test_model_sampling_maps_to_llama_preset_keys(temperature):
    cfg = copy.deepcopy(CFG)
    cfg["models"][0]["sampling"] = {
        "temperature": temperature,
        "top_p": 0.95,
        "top_k": 64,
        "repeat_penalty": 1.1,
    }

    parser = parse(render_presets(cfg, "/models", "Vulkan0"))

    assert {key: parser["gemma4"][key] for key in SAMPLER_KEYS} == {
        "temp": str(temperature),
        "top-p": "0.95",
        "top-k": "64",
        "repeat-penalty": "1.1",
    }
    assert all(key not in parser["*"] for key in SAMPLER_KEYS)
    assert all(key not in parser["ornith"] for key in SAMPLER_KEYS)


def test_empty_sampling_mapping_emits_no_sampler_keys():
    cfg = copy.deepcopy(CFG)
    cfg["models"][0]["sampling"] = {}

    section = parse(render_presets(cfg, "/models", "Vulkan0"))["gemma4"]

    assert all(key not in section for key in SAMPLER_KEYS)


def test_zero_sampling_values_are_not_dropped():
    cfg = copy.deepcopy(CFG)
    cfg["models"][0]["sampling"] = {
        "temperature": 0,
        "top_p": 0,
        "top_k": 0,
        "repeat_penalty": 1,
    }

    section = parse(render_presets(cfg, "/models", "Vulkan0"))["gemma4"]

    assert {key: section[key] for key in SAMPLER_KEYS} == {
        "temp": "0",
        "top-p": "0",
        "top-k": "0",
        "repeat-penalty": "1",
    }


def test_disabled_model_sampling_emits_no_section():
    cfg = copy.deepcopy(CFG)
    cfg["models"][0]["enabled"] = False
    cfg["models"][0]["sampling"] = {"temperature": 1.0}

    assert "gemma4" not in parse(render_presets(cfg, "/models", "Vulkan0"))


def test_flash_attn_off_renders_off():
    cfg = {**CFG, "runtime": {**CFG["runtime"], "flash_attn": False}}
    assert parse(render_presets(cfg, "/models", "Vulkan0"))["*"]["flash-attn"] == "off"


def test_write_presets_creates_parent_directories(tmp_path):
    target = tmp_path / "nested" / "presets.ini"
    write_presets(CFG, "/models", "Vulkan0", target)
    assert target.exists()
    assert "[gemma4]" in target.read_text()
