import os
import stat
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pylib.compose import render_compose, write_compose

CFG = {
    "version": 1,
    "server": {
        "host": "0.0.0.0",
        "port": 8000,
        "api_key": "test-api-key",
        "sleep_idle_seconds": 300,
    },
    "gpu": {
        "image": "ghcr.io/ggml-org/llama.cpp:server-vulkan",
    },
    "llm_server": {"enabled": True},
    "runtime": {
        "models_max": 1,
    },
    "resources": {
        "llm_server": {"cpus": 0, "memory_mib": 0},
        "omniroute": {"cpus": 0, "memory_mib": 0},
    },
    "omniroute": {
        "image": "docker.io/diegosouzapw/omniroute:latest",
        "port": 20128,
        "initial_password": "test-password",
    },
    "remote_setup": {
        "image": "docker.io/library/python:3.13-alpine",
        "port": 20130,
    },
}


def compose_dict(cfg=CFG):
    text = render_compose(
        cfg,
        models_dir="/home/user/llm-workspace/models",
        presets_path="/home/user/.config/llm-env/presets.ini",
        repo_root="/home/user/llm-env",
    )
    return text, yaml.safe_load(text)


def test_output_starts_with_a_comment_header():
    text, _ = compose_dict()
    assert text.startswith("# Generated by llm-env")


def test_service_uses_configured_image():
    _, document = compose_dict()
    assert document["services"]["llm-server"]["image"] == "ghcr.io/ggml-org/llama.cpp:server-vulkan"


def test_service_publishes_configured_port():
    _, document = compose_dict()
    assert document["services"]["llm-server"]["ports"] == ["8000:8000"]


def test_service_mounts_models_and_presets_read_only_with_selinux_label():
    _, document = compose_dict()
    volumes = document["services"]["llm-server"]["volumes"]
    assert "/home/user/llm-workspace/models:/models:ro,z" in volumes
    assert "/home/user/.config/llm-env/presets.ini:/etc/llama/presets.ini:ro,z" in volumes


def test_service_passes_the_dri_device():
    _, document = compose_dict()
    assert document["services"]["llm-server"]["devices"] == ["/dev/dri:/dev/dri"]


def test_service_sets_router_environment():
    _, document = compose_dict()
    env = document["services"]["llm-server"]["environment"]
    assert env["LLAMA_ARG_MODELS_PRESET"] == "/etc/llama/presets.ini"
    assert env["LLAMA_ARG_MODELS_MAX"] == "1"
    assert env["LLAMA_ARG_HOST"] == "0.0.0.0"
    assert env["LLAMA_ARG_PORT"] == "8000"
    assert env["LLAMA_API_KEY"] == "test-api-key"


def test_service_healthcheck_probes_127_0_0_1():
    _, document = compose_dict()
    healthcheck = document["services"]["llm-server"]["healthcheck"]
    assert healthcheck["test"] == [
        "CMD-SHELL",
        "curl -fsS http://127.0.0.1:8000/health || exit 1",
    ]


def test_service_restarts_on_failure():
    _, document = compose_dict()
    assert document["services"]["llm-server"]["restart"] == "on-failure"


def test_zero_resource_limits_are_omitted():
    _, document = compose_dict()
    service = document["services"]["llm-server"]
    assert "cpus" not in service
    assert "mem_limit" not in service


def test_nonzero_resource_limits_are_applied():
    cfg = {**CFG, "resources": {"llm_server": {"cpus": 6, "memory_mib": 28672}}}
    _, document = compose_dict(cfg)
    service = document["services"]["llm-server"]
    assert service["cpus"] == 6
    assert service["mem_limit"] == "28672m"


def test_sleep_idle_seconds_becomes_a_command_flag():
    _, document = compose_dict()
    assert document["services"]["llm-server"]["command"] == ["--sleep-idle-seconds", "300"]


def test_omniroute_service_uses_configured_image_and_port():
    _, document = compose_dict()
    omniroute = document["services"]["omniroute"]
    assert omniroute["image"] == "docker.io/diegosouzapw/omniroute:latest"
    assert omniroute["ports"] == ["0.0.0.0:20128:20128"]


def test_omniroute_service_mounts_a_named_data_volume():
    _, document = compose_dict()
    assert document["services"]["omniroute"]["volumes"] == ["omniroute-data:/app/data"]
    assert document["volumes"]["omniroute-data"] == {}


def test_omniroute_service_sets_its_environment():
    _, document = compose_dict()
    env = document["services"]["omniroute"]["environment"]
    assert env["PORT"] == "20128"
    assert env["OMNIROUTE_ALLOW_PRIVATE_PROVIDER_URLS"] == "true"
    assert env["INITIAL_PASSWORD"] == "test-password"


def test_omniroute_service_requires_an_api_key_on_its_client_api():
    """The service is published on 0.0.0.0 for LAN clients, so OmniRoute's
    default anonymous /v1/* access must be turned off -- otherwise the
    scoped keys remote-setup hands out are decorative."""
    _, document = compose_dict()
    env = document["services"]["omniroute"]["environment"]
    assert env["REQUIRE_API_KEY"] == "true"


def test_omniroute_service_healthcheck_runs_the_bundled_script():
    _, document = compose_dict()
    healthcheck = document["services"]["omniroute"]["healthcheck"]
    assert healthcheck["test"] == ["CMD", "node", "healthcheck.mjs"]


def test_omniroute_service_depends_on_a_healthy_llm_server():
    _, document = compose_dict()
    assert document["services"]["omniroute"]["depends_on"] == {
        "llm-server": {"condition": "service_healthy"}
    }


def test_omniroute_service_stop_grace_period_and_restart_policy():
    _, document = compose_dict()
    omniroute = document["services"]["omniroute"]
    assert omniroute["stop_grace_period"] == "40s"
    assert omniroute["restart"] == "unless-stopped"


def test_omniroute_zero_resource_limits_are_omitted():
    _, document = compose_dict()
    omniroute = document["services"]["omniroute"]
    assert "cpus" not in omniroute
    assert "mem_limit" not in omniroute


def test_omniroute_nonzero_resource_limits_are_applied():
    cfg = {**CFG, "resources": {**CFG["resources"], "omniroute": {"cpus": 1, "memory_mib": 1024}}}
    _, document = compose_dict(cfg)
    omniroute = document["services"]["omniroute"]
    assert omniroute["cpus"] == 1
    assert omniroute["mem_limit"] == "1024m"


def test_dollar_signs_in_secrets_are_escaped_against_compose_interpolation():
    cfg = {
        **CFG,
        "server": {**CFG["server"], "api_key": "sekret$with$dollars"},
        "omniroute": {
            **CFG["omniroute"],
            "initial_password": "pw$word",
        },
    }
    _, document = compose_dict(cfg)
    assert document["services"]["llm-server"]["environment"]["LLAMA_API_KEY"] == "sekret$$with$$dollars"
    omniroute_env = document["services"]["omniroute"]["environment"]
    assert omniroute_env["INITIAL_PASSWORD"] == "pw$$word"


def test_write_compose_creates_parent_directories(tmp_path):
    target = tmp_path / "nested" / "docker-compose.yml"
    write_compose(
        CFG, models_dir="/models", presets_path="/presets.ini", repo_root="/repo", path=target
    )
    assert target.exists()
    assert "llm-server" in yaml.safe_load(target.read_text())["services"]


def test_write_compose_sets_restrictive_file_mode(tmp_path):
    target = tmp_path / "docker-compose.yml"
    write_compose(
        CFG, models_dir="/models", presets_path="/presets.ini", repo_root="/repo", path=target
    )
    assert stat.S_IMODE(target.stat().st_mode) == 0o600


def test_write_compose_is_never_briefly_world_readable(tmp_path, monkeypatch):
    """The rendered file carries the master key, the dashboard password and
    the server API key. Under a 022 umask a plain write-then-chmod leaves it
    0644 for an instant; assert the content only ever exists behind 0600 by
    inspecting the source file at the moment it is published."""
    target = tmp_path / "docker-compose.yml"
    observed = {}
    real_replace = os.replace

    def spy_replace(src, dst, *args, **kwargs):
        observed["mode"] = stat.S_IMODE(os.stat(src).st_mode)
        observed["content"] = Path(src).read_text(encoding="utf-8")
        return real_replace(src, dst, *args, **kwargs)

    monkeypatch.setattr(os, "replace", spy_replace)
    # A fully permissive umask makes the "briefly 0644" bug reproducible:
    # with write-then-chmod the file would be created 0666 here.
    previous_umask = os.umask(0)
    try:
        write_compose(
            CFG,
            models_dir="/models",
            presets_path="/presets.ini",
            repo_root="/repo",
            omni_router_master_key="test-master-key",
            path=target,
        )
    finally:
        os.umask(previous_umask)

    assert observed["mode"] == 0o600
    assert "test-master-key" in observed["content"]
    assert stat.S_IMODE(target.stat().st_mode) == 0o600


def test_write_compose_failure_leaves_the_existing_file_intact(tmp_path, monkeypatch):
    """A crash mid-publish must not truncate or clobber a valid compose file,
    and must not leave a temp file behind."""
    target = tmp_path / "docker-compose.yml"
    write_compose(
        CFG, models_dir="/models", presets_path="/presets.ini", repo_root="/repo", path=target
    )
    original = target.read_text(encoding="utf-8")

    def boom(src, dst, *args, **kwargs):
        raise OSError("simulated failure while publishing")

    monkeypatch.setattr(os, "replace", boom)
    try:
        write_compose(
            CFG,
            models_dir="/other",
            presets_path="/presets.ini",
            repo_root="/repo",
            path=target,
        )
    except OSError:
        pass
    else:  # pragma: no cover - the monkeypatched replace always raises
        raise AssertionError("write_compose swallowed the failure")

    assert target.read_text(encoding="utf-8") == original
    assert stat.S_IMODE(target.stat().st_mode) == 0o600
    leftovers = [p.name for p in tmp_path.iterdir() if p.name != "docker-compose.yml"]
    assert leftovers == []


def test_remote_setup_service_uses_configured_image_and_port():
    _, document = compose_dict()
    remote_setup = document["services"]["remote-setup"]
    assert remote_setup["image"] == "docker.io/library/python:3.13-alpine"
    assert remote_setup["ports"] == ["0.0.0.0:20130:20130"]


def test_remote_setup_service_mounts_pylib_and_a_named_data_volume():
    _, document = compose_dict()
    volumes = document["services"]["remote-setup"]["volumes"]
    assert "/home/user/llm-env/pylib:/app/pylib:ro,z" in volumes
    assert (
        "/home/user/llm-env/setup/update-opencode-config.mjs"
        ":/app/setup/update-opencode-config.mjs:ro,z" in volumes
    )
    assert "remote-setup-data:/app/data" in volumes
    assert document["volumes"]["remote-setup-data"] == {}


def test_remote_setup_mounts_the_shared_agent_client_library():
    _, document = compose_dict(CFG)
    volumes = document["services"]["remote-setup"]["volumes"]
    assert any(v.endswith("/setup/lib:/app/setup/lib:ro,z") for v in volumes)


def test_remote_setup_service_command_runs_the_module():
    _, document = compose_dict()
    assert document["services"]["remote-setup"]["command"] == [
        "python3", "-m", "pylib.remote_setup",
    ]


def test_remote_setup_service_working_dir_is_app():
    _, document = compose_dict()
    assert document["services"]["remote-setup"]["working_dir"] == "/app"


def test_remote_setup_environment_carries_omniroute_and_master_key():
    text = render_compose(
        CFG,
        models_dir="/models",
        presets_path="/presets.ini",
        repo_root="/repo",
        omni_router_master_key="test-master-key",
    )
    document = yaml.safe_load(text)
    env = document["services"]["remote-setup"]["environment"]
    assert env["OMNI_ROUTER_MASTER_KEY"] == "test-master-key"
    assert env["REMOTE_SETUP_PORT"] == "20130"
    assert env["OMNIROUTE_INTERNAL_URL"] == "http://omniroute:20128"
    assert env["OMNIROUTE_PORT"] == "20128"
    assert env["OMNIROUTE_DASHBOARD_PASSWORD"] == "test-password"


def test_remote_setup_environment_defaults_master_key_to_empty_string():
    _, document = compose_dict()
    assert document["services"]["remote-setup"]["environment"]["OMNI_ROUTER_MASTER_KEY"] == ""


def test_remote_setup_models_json_lists_only_enabled_models_alias_ctx_and_output_tokens():
    cfg = {
        **CFG,
        "models": [
            {"alias": "a", "enabled": True, "ctx_size": 8192, "client_max_output_tokens": 4096},
            {"alias": "b", "enabled": False, "ctx_size": 8192, "client_max_output_tokens": 4096},
        ],
    }
    _, document = compose_dict(cfg)
    import json as _json
    models_json = _json.loads(document["services"]["remote-setup"]["environment"]["MODELS_JSON"])
    assert models_json == [{"alias": "a", "ctx_size": 8192, "client_max_output_tokens": 4096}]


def test_remote_setup_models_json_is_empty_when_llm_server_disabled():
    cfg = {
        **CFG,
        "llm_server": {"enabled": False},
        "models": [
            {"alias": "a", "enabled": True, "ctx_size": 8192, "client_max_output_tokens": 4096},
        ],
    }
    _, document = compose_dict(cfg)
    import json as _json
    models_json = _json.loads(document["services"]["remote-setup"]["environment"]["MODELS_JSON"])
    assert models_json == []


def test_remote_setup_service_depends_on_omniroute_healthy():
    _, document = compose_dict()
    assert document["services"]["remote-setup"]["depends_on"] == {
        "omniroute": {"condition": "service_healthy"},
    }


def test_remote_setup_service_has_a_healthcheck():
    _, document = compose_dict()
    healthcheck = document["services"]["remote-setup"]["healthcheck"]
    test = healthcheck["test"]
    assert test[:3] == ["CMD", "python3", "-c"]
    assert "/setup.sh" in test[3]
    assert "127.0.0.1:20130" in test[3]


def test_llm_server_service_omitted_when_disabled():
    cfg = {**CFG, "llm_server": {"enabled": False}}
    _, document = compose_dict(cfg)
    assert "llm-server" not in document["services"]
    assert "omniroute" in document["services"]
    assert "remote-setup" in document["services"]


def test_omniroute_depends_on_llm_server_omitted_when_disabled():
    cfg = {**CFG, "llm_server": {"enabled": False}}
    _, document = compose_dict(cfg)
    assert "depends_on" not in document["services"]["omniroute"]


def test_llm_server_service_present_when_llm_server_key_absent():
    """Default-true: a config with no llm_server key at all (pre-migration)
    must still render llm-server."""
    cfg = {key: value for key, value in CFG.items() if key != "llm_server"}
    _, document = compose_dict(cfg)
    assert "llm-server" in document["services"]
    assert document["services"]["omniroute"]["depends_on"] == {
        "llm-server": {"condition": "service_healthy"}
    }


def test_remote_setup_depends_on_omniroute_unaffected_by_llm_server_disabled():
    cfg = {**CFG, "llm_server": {"enabled": False}}
    _, document = compose_dict(cfg)
    assert document["services"]["remote-setup"]["depends_on"] == {
        "omniroute": {"condition": "service_healthy"}
    }


def test_omniroute_depends_on_key_ordering_preserved_when_enabled():
    """Regression test: depends_on must appear between stop_grace_period and
    restart in the rendered YAML (yaml.safe_dump preserves dict insertion order).
    When enabled, the output must be byte-identical to before this feature."""
    _, document = compose_dict()
    omniroute_keys = list(document["services"]["omniroute"].keys())
    stop_grace_period_idx = omniroute_keys.index("stop_grace_period")
    depends_on_idx = omniroute_keys.index("depends_on")
    restart_idx = omniroute_keys.index("restart")
    assert stop_grace_period_idx < depends_on_idx < restart_idx
