import stat
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pylib.compose import render_compose, write_compose

CFG = {
    "version": 1,
    "server": {
        "host": "0.0.0.0",
        "port": 8000,
        "api_key": "test-api-key",
        "sleep_idle_seconds": 300,
    },
    "gpu": {
        "image": "ghcr.io/ggml-org/llama.cpp:server-vulkan",
    },
    "runtime": {
        "models_max": 1,
    },
    "resources": {
        "llm_server": {"cpus": 0, "memory_mib": 0},
        "omniroute": {"cpus": 0, "memory_mib": 0},
    },
    "omniroute": {
        "image": "docker.io/diegosouzapw/omniroute:latest",
        "port": 20128,
        "initial_password": "test-password",
    },
}


def compose_dict(cfg=CFG):
    text = render_compose(cfg, models_dir="/home/user/llm-workspace/models", presets_path="/home/user/.config/llm-env/presets.ini")
    return text, yaml.safe_load(text)


def test_output_starts_with_a_comment_header():
    text, _ = compose_dict()
    assert text.startswith("# Generated by llm-env")


def test_service_uses_configured_image():
    _, document = compose_dict()
    assert document["services"]["llm-server"]["image"] == "ghcr.io/ggml-org/llama.cpp:server-vulkan"


def test_service_publishes_configured_port():
    _, document = compose_dict()
    assert document["services"]["llm-server"]["ports"] == ["8000:8000"]


def test_service_mounts_models_and_presets_read_only_with_selinux_label():
    _, document = compose_dict()
    volumes = document["services"]["llm-server"]["volumes"]
    assert "/home/user/llm-workspace/models:/models:ro,z" in volumes
    assert "/home/user/.config/llm-env/presets.ini:/etc/llama/presets.ini:ro,z" in volumes


def test_service_passes_the_dri_device():
    _, document = compose_dict()
    assert document["services"]["llm-server"]["devices"] == ["/dev/dri:/dev/dri"]


def test_service_sets_router_environment():
    _, document = compose_dict()
    env = document["services"]["llm-server"]["environment"]
    assert env["LLAMA_ARG_MODELS_PRESET"] == "/etc/llama/presets.ini"
    assert env["LLAMA_ARG_MODELS_MAX"] == "1"
    assert env["LLAMA_ARG_HOST"] == "0.0.0.0"
    assert env["LLAMA_ARG_PORT"] == "8000"
    assert env["LLAMA_API_KEY"] == "test-api-key"


def test_service_healthcheck_probes_127_0_0_1():
    _, document = compose_dict()
    healthcheck = document["services"]["llm-server"]["healthcheck"]
    assert healthcheck["test"] == [
        "CMD-SHELL",
        "curl -fsS http://127.0.0.1:8000/health || exit 1",
    ]


def test_service_restarts_on_failure():
    _, document = compose_dict()
    assert document["services"]["llm-server"]["restart"] == "on-failure"


def test_zero_resource_limits_are_omitted():
    _, document = compose_dict()
    service = document["services"]["llm-server"]
    assert "cpus" not in service
    assert "mem_limit" not in service


def test_nonzero_resource_limits_are_applied():
    cfg = {**CFG, "resources": {"llm_server": {"cpus": 6, "memory_mib": 28672}}}
    _, document = compose_dict(cfg)
    service = document["services"]["llm-server"]
    assert service["cpus"] == 6
    assert service["mem_limit"] == "28672m"


def test_sleep_idle_seconds_becomes_a_command_flag():
    _, document = compose_dict()
    assert document["services"]["llm-server"]["command"] == ["--sleep-idle-seconds", "300"]


def test_omniroute_service_uses_configured_image_and_port():
    _, document = compose_dict()
    omniroute = document["services"]["omniroute"]
    assert omniroute["image"] == "docker.io/diegosouzapw/omniroute:latest"
    assert omniroute["ports"] == ["127.0.0.1:20128:20128"]


def test_omniroute_service_mounts_a_named_data_volume():
    _, document = compose_dict()
    assert document["services"]["omniroute"]["volumes"] == ["omniroute-data:/app/data"]
    assert document["volumes"] == {"omniroute-data": {}}


def test_omniroute_service_sets_its_environment():
    _, document = compose_dict()
    env = document["services"]["omniroute"]["environment"]
    assert env["PORT"] == "20128"
    assert env["OMNIROUTE_ALLOW_PRIVATE_PROVIDER_URLS"] == "true"
    assert env["INITIAL_PASSWORD"] == "test-password"


def test_omniroute_service_healthcheck_runs_the_bundled_script():
    _, document = compose_dict()
    healthcheck = document["services"]["omniroute"]["healthcheck"]
    assert healthcheck["test"] == ["CMD", "node", "healthcheck.mjs"]


def test_omniroute_service_depends_on_a_healthy_llm_server():
    _, document = compose_dict()
    assert document["services"]["omniroute"]["depends_on"] == {
        "llm-server": {"condition": "service_healthy"}
    }


def test_omniroute_service_stop_grace_period_and_restart_policy():
    _, document = compose_dict()
    omniroute = document["services"]["omniroute"]
    assert omniroute["stop_grace_period"] == "40s"
    assert omniroute["restart"] == "unless-stopped"


def test_omniroute_zero_resource_limits_are_omitted():
    _, document = compose_dict()
    omniroute = document["services"]["omniroute"]
    assert "cpus" not in omniroute
    assert "mem_limit" not in omniroute


def test_omniroute_nonzero_resource_limits_are_applied():
    cfg = {**CFG, "resources": {**CFG["resources"], "omniroute": {"cpus": 1, "memory_mib": 1024}}}
    _, document = compose_dict(cfg)
    omniroute = document["services"]["omniroute"]
    assert omniroute["cpus"] == 1
    assert omniroute["mem_limit"] == "1024m"


def test_dollar_signs_in_secrets_are_escaped_against_compose_interpolation():
    cfg = {
        **CFG,
        "server": {**CFG["server"], "api_key": "sekret$with$dollars"},
        "omniroute": {
            **CFG["omniroute"],
            "initial_password": "pw$word",
        },
    }
    _, document = compose_dict(cfg)
    assert document["services"]["llm-server"]["environment"]["LLAMA_API_KEY"] == "sekret$$with$$dollars"
    omniroute_env = document["services"]["omniroute"]["environment"]
    assert omniroute_env["INITIAL_PASSWORD"] == "pw$$word"


def test_write_compose_creates_parent_directories(tmp_path):
    target = tmp_path / "nested" / "docker-compose.yml"
    write_compose(CFG, models_dir="/models", presets_path="/presets.ini", path=target)
    assert target.exists()
    assert "llm-server" in yaml.safe_load(target.read_text())["services"]


def test_write_compose_sets_restrictive_file_mode(tmp_path):
    target = tmp_path / "docker-compose.yml"
    write_compose(CFG, models_dir="/models", presets_path="/presets.ini", path=target)
    assert stat.S_IMODE(target.stat().st_mode) == 0o600
