#!/usr/bin/env bash
set -euo pipefail

echo "make prerequisites Confirm and install host prerequisites"
echo "make setup         Interactive configuration"
echo "make setup-local-llm-agents Configure normal Pi and OpenCode local providers"
echo "make start         Start the LLM server"
echo "make stop          Stop the LLM server"
echo "make restart       Restart the LLM server"
echo "make check-setup   Validate config, image, models, GPU (offline)"
echo "make check-server  Validate the running server API (online)"
echo "make check-with-agents Opt-in independent agent inference checks"
echo "make benchmark     Benchmark Vulkan and record results, with CPU fallback"
echo "make key-reset     Generate a new API key"
echo "make show-secrets  Print the API key and OmniRoute dashboard password"
echo "make enable-boot   Start automatically at boot"
echo "make disable-boot  Do not start at boot"
echo "make status        Show service status"
echo "make gpu-status    Show live dGPU contention; optionally migrate offenders to the iGPU"
echo "make desktop-gpu-reset Remove a leftover desktop default-GPU override (use 'cardwire' to choose the default GPU)"
echo "make desktop-gpu-status Show detected GPUs and which one is active"
echo "make provider-provision Import local CLI provider sessions (Codex) into OmniRoute"
echo "make update-omniroute Pull a newer OmniRoute image if one is published, then stop/start"
echo "make check-provider-tokens Flag any OmniRoute provider connection needing reauthentication"
echo "make enable-token-check Install a daily timer for check-provider-tokens (desktop notify)"
echo "make disable-token-check Remove the daily provider-token-check timer"
echo "make logs          Follow service logs"
echo "make validate      Run shellcheck and ruff"
echo "make test          Run the Python test suite"
echo "make clean         Remove config, unit, and images"
echo "make prune         Remove config, unit, images, AND downloaded models (destructive)"
