#!/usr/bin/env bash
# enable-token-check.sh — install and enable a daily systemd --user timer
# that runs scripts/check-provider-tokens.sh and desktop-notifies (via
# notify-send, when available) on any connection needing reauthentication.
set -euo pipefail
# shellcheck disable=SC1091 # Resolved from this script at runtime.
# shellcheck source=../tools/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/../tools/lib.sh"

require_cmd systemctl

[ -f "$CONFIG_PATH" ] || die "no config at ${CONFIG_PATH}; run 'make setup' first"

service_unit="${HOME}/.config/systemd/user/${TOKEN_CHECK_UNIT_NAME}.service"
timer_unit="${HOME}/.config/systemd/user/${TOKEN_CHECK_UNIT_NAME}.timer"
mkdir -p "$(dirname "$service_unit")"

cat > "$service_unit" <<EOF
# Generated by enable-token-check.sh. Edits will be overwritten.
[Unit]
Description=llm-env OmniRoute provider token health check
After=network-online.target

[Service]
Type=oneshot
# systemd --user services do not inherit the interactive shell's PATH (no
# profile/rc files are sourced), so tools installed under the user's own
# bin directories -- yq via pipx/uv-tool/cargo-install, commonly under
# ~/.local/bin -- would otherwise resolve to nothing here even though
# 'bash scripts/check-provider-tokens.sh' works fine from a terminal.
Environment=PATH=%h/.local/bin:/usr/local/bin:/usr/bin:/bin
ExecStart=/usr/bin/bash ${REPO_DIR}/scripts/check-provider-tokens.sh
EOF
chmod 600 "$service_unit"
log_info "wrote ${service_unit}"

cat > "$timer_unit" <<EOF
# Generated by enable-token-check.sh. Edits will be overwritten.
[Unit]
Description=Daily OmniRoute provider token health check

[Timer]
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
EOF
chmod 600 "$timer_unit"
log_info "wrote ${timer_unit}"

systemctl --user daemon-reload
systemctl --user enable --now "${TOKEN_CHECK_UNIT_NAME}.timer"
log_info "enabled ${TOKEN_CHECK_UNIT_NAME}.timer (runs daily; catches up after sleep/shutdown via Persistent=true)"
log_info "check its schedule: systemctl --user list-timers ${TOKEN_CHECK_UNIT_NAME}.timer"
log_info "run it right now:   systemctl --user start ${TOKEN_CHECK_UNIT_NAME}.service"
