#!/usr/bin/env bash
# render-unit.sh — generate presets and the Quadlet unit without starting it.
set -euo pipefail
# shellcheck disable=SC1091 # Resolved from this script at runtime.
# shellcheck source=../tools/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/../tools/lib.sh"

require_cmd uv jq yq podman systemctl

[ -f "$CONFIG_PATH" ] || die "no config at ${CONFIG_PATH}; run 'make setup' first"
migrate_config_file || die "configuration migration failed"

backend="$(yq -r '.gpu.backend' "$CONFIG_PATH")"
image="$(yq -r '.gpu.image' "$CONFIG_PATH")"
device_name="$(yq -r '.gpu.device_name' "$CONFIG_PATH")"
load_server_config
# shellcheck disable=SC2153 # HOST/PORT/API_KEY are set by load_server_config() in ../tools/lib.sh.
host="$HOST"
# shellcheck disable=SC2153
port="$PORT"
# shellcheck disable=SC2153
api_key="$API_KEY"
sleep_idle="$(yq -r '.server.sleep_idle_seconds' "$CONFIG_PATH")"
models_max="$(yq -r '.runtime.models_max' "$CONFIG_PATH")"

[ "$models_max" -gt 0 ] || die "no models enabled; run 'make setup'"

log_step "Resolving the GPU device"
device="all"
if [ "$backend" != "cpu" ] && [ -n "$device_name" ] && [ "$device_name" != "null" ]; then
    listing_file="$(mktemp)"
    podman run --rm --device /dev/dri --entrypoint /app/llama-server \
        "$image" --list-devices >"$listing_file" 2>/dev/null || true
    if resolved="$(llmenv resolve-device --device-name "$device_name" \
                   --listing-file "$listing_file")"; then
        device="$(echo "$resolved" | jq -r '.device')"
        log_info "pinned to ${device} (${device_name})"
    else
        log_warn "could not resolve ${device_name}; offloading to all devices"
    fi
    rm -f "$listing_file"
fi

log_step "Generating presets.ini"
presets_path="${HOME}/.config/llm-env/presets.ini"
llmenv --config "$CONFIG_PATH" presets \
    --models-dir /models --device "$device" --output "$presets_path" >/dev/null
log_info "wrote ${presets_path}"

log_step "Rendering the quadlet unit"
mkdir -p "$QUADLET_DIR"
device_lines="AddDevice=/dev/dri"

mdns_unit="${HOME}/.config/systemd/user/${UNIT_NAME}-mdns.service"
mdns_wants=""
if avahi_publish="$(command -v avahi-publish 2>/dev/null)"; then
    mkdir -p "$(dirname "$mdns_unit")"
    rm -f "${QUADLET_DIR}/${UNIT_NAME}-mdns.service"
    mdns_name="$(yq -r '.server.mdns_name' "$CONFIG_PATH")"
    curl_path="$(command -v curl)"
    cat > "$mdns_unit" <<EOF
# Generated by render-unit.sh. Publishes only after the router is healthy.
[Unit]
Description=llama.cpp router mDNS publication
Requires=${UNIT_NAME}.service
After=${UNIT_NAME}.service
BindsTo=${UNIT_NAME}.service
PartOf=${UNIT_NAME}.service

[Service]
Type=simple
ExecStartPre=/usr/bin/bash -c 'i=0; while [ \$\$i -lt ${LLM_ENV_HEALTH_TIMEOUT_SECONDS} ]; do ${curl_path} -fsS -o /dev/null http://127.0.0.1:${port}/health && exit 0; i=\$\$((i + 1)); sleep 1; done; exit 1'
ExecStart=${avahi_publish} -s ${mdns_name} _http._tcp ${port}
Restart=on-failure
RestartSec=2
EOF
    chmod 600 "$mdns_unit"
    mdns_wants="Wants=${UNIT_NAME}-mdns.service"
    log_info "wrote ${mdns_unit}"
else
    rm -f "$mdns_unit" "${QUADLET_DIR}/${UNIT_NAME}-mdns.service"
fi

start_at_boot="$(yq -r '.server.start_at_boot // false' "$CONFIG_PATH")"
if [ "$start_at_boot" = "true" ]; then
    install_section=$'\n[Install]\nWantedBy=default.target'
else
    install_section=""
fi

cat > "${QUADLET_DIR}/${UNIT_NAME}.container" <<EOF
# Generated by render-unit.sh from ${CONFIG_PATH}. Edits will be overwritten.
[Unit]
Description=llama.cpp router server (${backend})
After=network-online.target
${mdns_wants}

[Container]
Image=${image}
ContainerName=${UNIT_NAME}
${device_lines}
Volume=${MODELS_DIR}:/models:ro,z
Volume=${presets_path}:/etc/llama/presets.ini:ro,z
PublishPort=${port}:${port}
Environment=LLAMA_ARG_MODELS_PRESET=/etc/llama/presets.ini
Environment=LLAMA_ARG_MODELS_MAX=${models_max}
Environment=LLAMA_ARG_HOST=${host}
Environment=LLAMA_ARG_PORT=${port}
Environment=LLAMA_API_KEY=${api_key}
Exec=--sleep-idle-seconds ${sleep_idle}
HealthCmd=curl -fsS http://127.0.0.1:${port}/health || exit 1
HealthInterval=10s
HealthRetries=30
HealthStartPeriod=20s

[Service]
Restart=on-failure
TimeoutStartSec=300
${install_section}
EOF
log_info "wrote ${QUADLET_DIR}/${UNIT_NAME}.container"
chmod 600 "${QUADLET_DIR}/${UNIT_NAME}.container"
systemctl --user daemon-reload
