"""Render docker-compose.yml from models.yml.

Builds the compose document as a Python dict and dumps it with
yaml.safe_dump, so the output is always syntactically valid — the same
"structured data in, generated file out" shape pylib/presets.py uses for
presets.ini via configparser.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

HEADER_COMMENT = "# Generated by llm-env. Do not edit; regenerated on every start.\n"


def render_compose(cfg: dict[str, Any], *, models_dir: str, presets_path: str) -> str:
    server = cfg["server"]
    gpu = cfg["gpu"]
    runtime = cfg["runtime"]
    llm_server_resources = cfg.get("resources", {}).get("llm_server", {})

    service: dict[str, Any] = {
        "image": gpu["image"],
        "container_name": "llm-server",
        # /dev/dri is always passed through; the specific GPU device is
        # selected inside presets.ini, not at the container level.
        "devices": ["/dev/dri:/dev/dri"],
        "volumes": [
            # `,z` relabels the bind mount for SELinux — required on Fedora
            # Atomic hosts, understood by the podman compose provider.
            f"{models_dir}:/models:ro,z",
            f"{presets_path}:/etc/llama/presets.ini:ro,z",
        ],
        "ports": [f"{server['port']}:{server['port']}"],
        "environment": {
            "LLAMA_ARG_MODELS_PRESET": "/etc/llama/presets.ini",
            "LLAMA_ARG_MODELS_MAX": runtime["models_max"],
            "LLAMA_ARG_HOST": server["host"],
            "LLAMA_ARG_PORT": server["port"],
            "LLAMA_API_KEY": server["api_key"],
        },
        "command": ["--sleep-idle-seconds", str(server["sleep_idle_seconds"])],
        "healthcheck": {
            "test": [
                "CMD-SHELL",
                f"curl -fsS http://127.0.0.1:{server['port']}/health || exit 1",
            ],
            "interval": "10s",
            "retries": 30,
            "start_period": "20s",
        },
        "restart": "on-failure",
    }

    cpus = llm_server_resources.get("cpus")
    if cpus:
        service["cpus"] = cpus
    memory_mib = llm_server_resources.get("memory_mib")
    if memory_mib:
        service["mem_limit"] = f"{memory_mib}m"

    document = {"services": {"llm-server": service}}
    return HEADER_COMMENT + yaml.safe_dump(
        document, sort_keys=False, default_flow_style=False
    )


def write_compose(
    cfg: dict[str, Any], *, models_dir: str, presets_path: str, path: Path
) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        render_compose(cfg, models_dir=models_dir, presets_path=presets_path),
        encoding="utf-8",
    )
