"""Render docker-compose.yml from models.yml.

Builds the compose document as a Python dict and dumps it with
yaml.safe_dump, so the output is always syntactically valid — the same
"structured data in, generated file out" shape pylib/presets.py uses for
presets.ini via configparser.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

HEADER_COMMENT = "# Generated by llm-env. Do not edit; regenerated on every start.\n"


def render_compose(cfg: dict[str, Any], *, models_dir: str, presets_path: str) -> str:
    server = cfg["server"]
    gpu = cfg["gpu"]
    runtime = cfg["runtime"]
    llm_server_resources = cfg.get("resources", {}).get("llm_server", {})
    omniroute_cfg = cfg.get("omniroute", {})
    omniroute_resources = cfg.get("resources", {}).get("omniroute", {})

    service: dict[str, Any] = {
        "image": gpu["image"],
        "container_name": "llm-server",
        # /dev/dri is always passed through; the specific GPU device is
        # selected inside presets.ini, not at the container level.
        "devices": ["/dev/dri:/dev/dri"],
        "volumes": [
            # `,z` relabels the bind mount for SELinux — required on Fedora
            # Atomic hosts, understood by the podman compose provider.
            f"{models_dir}:/models:ro,z",
            f"{presets_path}:/etc/llama/presets.ini:ro,z",
        ],
        "ports": [f"{server['port']}:{server['port']}"],
        "environment": {
            "LLAMA_ARG_MODELS_PRESET": "/etc/llama/presets.ini",
            "LLAMA_ARG_MODELS_MAX": str(runtime["models_max"]),
            "LLAMA_ARG_HOST": server["host"],
            "LLAMA_ARG_PORT": str(server["port"]),
            "LLAMA_API_KEY": server["api_key"],
        },
        "command": ["--sleep-idle-seconds", str(server["sleep_idle_seconds"])],
        "healthcheck": {
            "test": [
                "CMD-SHELL",
                f"curl -fsS http://127.0.0.1:{server['port']}/health || exit 1",
            ],
            "interval": "10s",
            "retries": 30,
            "start_period": "20s",
        },
        "restart": "on-failure",
    }

    cpus = llm_server_resources.get("cpus")
    if cpus:
        service["cpus"] = cpus
    memory_mib = llm_server_resources.get("memory_mib")
    if memory_mib:
        service["mem_limit"] = f"{memory_mib}m"

    omniroute_port = omniroute_cfg.get("port", 20128)
    omniroute_service: dict[str, Any] = {
        "image": omniroute_cfg.get("image", "docker.io/diegosouzapw/omniroute:latest"),
        "container_name": "omniroute",
        "ports": [f"{omniroute_port}:{omniroute_port}"],
        "volumes": ["omniroute-data:/app/data"],
        "environment": {
            "PORT": str(omniroute_port),
            "OMNIROUTE_CLI_TOKEN": omniroute_cfg.get("cli_token", ""),
            "OMNIROUTE_ALLOW_PRIVATE_PROVIDER_URLS": "true",
            "INITIAL_PASSWORD": omniroute_cfg.get("initial_password", ""),
        },
        "healthcheck": {
            "test": ["CMD", "node", "healthcheck.mjs"],
            "interval": "30s",
            "timeout": "5s",
            "retries": 3,
            "start_period": "15s",
        },
        "stop_grace_period": "40s",
        "depends_on": {"llm-server": {"condition": "service_healthy"}},
        "restart": "unless-stopped",
    }
    omniroute_cpus = omniroute_resources.get("cpus")
    if omniroute_cpus:
        omniroute_service["cpus"] = omniroute_cpus
    omniroute_memory_mib = omniroute_resources.get("memory_mib")
    if omniroute_memory_mib:
        omniroute_service["mem_limit"] = f"{omniroute_memory_mib}m"

    document = {
        "services": {"llm-server": service, "omniroute": omniroute_service},
        "volumes": {"omniroute-data": {}},
    }
    return HEADER_COMMENT + yaml.safe_dump(
        document, sort_keys=False, default_flow_style=False
    )


def write_compose(
    cfg: dict[str, Any], *, models_dir: str, presets_path: str, path: Path
) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        render_compose(cfg, models_dir=models_dir, presets_path=presets_path),
        encoding="utf-8",
    )
