"""Render docker-compose.yml from models.yml.

Builds the compose document as a Python dict and dumps it with
yaml.safe_dump, so the output is always syntactically valid — the same
"structured data in, generated file out" shape pylib/presets.py uses for
presets.ini via configparser.
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any

import yaml

HEADER_COMMENT = "# Generated by llm-env. Do not edit; regenerated on every start.\n"


def _dollar_escape(value: str) -> str:
    """Escape literal '$' so podman-compose's $VAR/${VAR} interpolation doesn't
    expand it or leak host environment data into the container."""
    return value.replace("$", "$$")


def render_compose(
    cfg: dict[str, Any],
    *,
    models_dir: str,
    presets_path: str,
    repo_root: str,
    omni_router_master_key: str = "",
) -> str:
    server = cfg["server"]
    gpu = cfg["gpu"]
    runtime = cfg["runtime"]
    llm_server_enabled = cfg.get("llm_server", {}).get("enabled", True)
    llm_server_resources = cfg.get("resources", {}).get("llm_server", {})
    omniroute_cfg = cfg.get("omniroute", {})
    omniroute_resources = cfg.get("resources", {}).get("omniroute", {})

    models_dir = _dollar_escape(models_dir)
    presets_path = _dollar_escape(presets_path)

    service: dict[str, Any] = {
        "image": _dollar_escape(gpu["image"]),
        "container_name": "llm-server",
        # /dev/dri is always passed through; the specific GPU device is
        # selected inside presets.ini, not at the container level.
        "devices": ["/dev/dri:/dev/dri"],
        "volumes": [
            # `,z` relabels the bind mount for SELinux — required on Fedora
            # Atomic hosts, understood by the podman compose provider.
            f"{models_dir}:/models:ro,z",
            f"{presets_path}:/etc/llama/presets.ini:ro,z",
        ],
        "ports": [f"{server['port']}:{server['port']}"],
        "environment": {
            "LLAMA_ARG_MODELS_PRESET": "/etc/llama/presets.ini",
            "LLAMA_ARG_MODELS_MAX": str(runtime["models_max"]),
            "LLAMA_ARG_HOST": _dollar_escape(server["host"]),
            "LLAMA_ARG_PORT": str(server["port"]),
            "LLAMA_API_KEY": _dollar_escape(server["api_key"]),
        },
        "command": ["--sleep-idle-seconds", str(server["sleep_idle_seconds"])],
        "healthcheck": {
            "test": [
                "CMD-SHELL",
                f"curl -fsS http://127.0.0.1:{server['port']}/health || exit 1",
            ],
            "interval": "10s",
            "retries": 30,
            "start_period": "20s",
        },
        "restart": "on-failure",
    }

    cpus = llm_server_resources.get("cpus")
    if cpus:
        service["cpus"] = cpus
    memory_mib = llm_server_resources.get("memory_mib")
    if memory_mib:
        service["mem_limit"] = f"{memory_mib}m"

    omniroute_port = omniroute_cfg.get("port", 20128)
    omniroute_service: dict[str, Any] = {
        "image": _dollar_escape(
            omniroute_cfg.get("image", "docker.io/diegosouzapw/omniroute:latest")
        ),
        "container_name": "omniroute",
        "ports": [f"0.0.0.0:{omniroute_port}:{omniroute_port}"],
        "volumes": ["omniroute-data:/app/data"],
        "environment": {
            "PORT": str(omniroute_port),
            "OMNIROUTE_ALLOW_PRIVATE_PROVIDER_URLS": "true",
            # OmniRoute defaults REQUIRE_API_KEY to "false", which makes its
            # /v1/* client API anonymous-by-default: an unauthenticated
            # request is allowed, AND a request carrying an *invalid* bearer
            # silently degrades to anonymous instead of being rejected
            # (OmniRoute's own src/server/authz/policies/clientApi.ts). Since
            # this service publishes on 0.0.0.0 so LAN machines can reach it,
            # leaving the default would let any host on the network call
            # /v1/chat/completions with no credential at all -- and would make
            # the scoped API keys handed out by remote-setup /config
            # unrevokable in practice. Enforce real key validation instead.
            "REQUIRE_API_KEY": "true",
            "INITIAL_PASSWORD": _dollar_escape(omniroute_cfg.get("initial_password", "")),
        },
        "healthcheck": {
            "test": ["CMD", "node", "healthcheck.mjs"],
            # Local loopback probe of an already-running node process --
            # 5s is plenty even under load, and a short interval matters
            # more than a long timeout for how fast `make start` reports
            # ready: podman marks the container healthy on the first
            # successful probe, so a shorter interval means less time spent
            # waiting on a service that finished starting well before the
            # next check was due.
            "interval": "5s",
            "timeout": "3s",
            "retries": 5,
            "start_period": "10s",
        },
        "stop_grace_period": "40s",
        "depends_on": {"llm-server": {"condition": "service_healthy"}},
        "restart": "unless-stopped",
    }
    if not llm_server_enabled:
        del omniroute_service["depends_on"]
    omniroute_cpus = omniroute_resources.get("cpus")
    if omniroute_cpus:
        omniroute_service["cpus"] = omniroute_cpus
    omniroute_memory_mib = omniroute_resources.get("memory_mib")
    if omniroute_memory_mib:
        omniroute_service["mem_limit"] = f"{omniroute_memory_mib}m"

    remote_setup_cfg = cfg.get("remote_setup", {})
    remote_setup_port = remote_setup_cfg.get("port", 20130)
    # No llama.cpp instance ever runs in this mode (Task: GPU-optional setup),
    # so a remote machine's setup.sh must never be handed "enabled" llama-cpp
    # models that don't actually exist behind any OmniRoute connection --
    # leftover `enabled: true` rows in models.yml are otherwise vestigial and
    # would silently create dead provider entries on the remote machine.
    enabled_models = (
        [
            {
                "alias": model["alias"],
                "ctx_size": model["ctx_size"],
                "client_max_output_tokens": model["client_max_output_tokens"],
            }
            for model in cfg.get("models", [])
            if model.get("enabled")
        ]
        if llm_server_enabled
        else []
    )
    remote_setup_service: dict[str, Any] = {
        "image": _dollar_escape(
            remote_setup_cfg.get("image", "docker.io/library/python:3.13-alpine")
        ),
        "container_name": "remote-setup",
        "working_dir": "/app",
        "volumes": [
            f"{_dollar_escape(repo_root)}/pylib:/app/pylib:ro,z",
            # update-opencode-config.mjs is NOT served over HTTP (the design
            # defines exactly two public routes, /setup.sh and /config) --
            # it's mounted here so pylib/remote_setup.py can read its
            # content at script-render time and embed it verbatim into the
            # generated /setup.sh response via a bash heredoc. Mounted
            # explicitly since only pylib/ is otherwise in view.
            f"{_dollar_escape(repo_root)}/setup/update-opencode-config.mjs:/app/setup/update-opencode-config.mjs:ro,z",
            # setup/lib/install-agent-clients.sh (Task 1's shared library):
            # not served over HTTP either -- render_setup_script() reads it
            # and embeds it verbatim into /setup.sh via the same heredoc
            # technique used for update-opencode-config.mjs above.
            f"{_dollar_escape(repo_root)}/setup/lib:/app/setup/lib:ro,z",
            "remote-setup-data:/app/data",
        ],
        "ports": [f"0.0.0.0:{remote_setup_port}:{remote_setup_port}"],
        "command": ["python3", "-m", "pylib.remote_setup"],
        "environment": {
            "OMNI_ROUTER_MASTER_KEY": _dollar_escape(omni_router_master_key),
            "REMOTE_SETUP_PORT": str(remote_setup_port),
            "OMNIROUTE_INTERNAL_URL": f"http://omniroute:{omniroute_port}",
            "OMNIROUTE_PORT": str(omniroute_port),
            "OMNIROUTE_DASHBOARD_PASSWORD": _dollar_escape(
                omniroute_cfg.get("initial_password", "")
            ),
            "MODELS_JSON": _dollar_escape(json.dumps(enabled_models)),
        },
        "depends_on": {"omniroute": {"condition": "service_healthy"}},
        "restart": "unless-stopped",
        "healthcheck": {
            "test": [
                "CMD",
                "python3",
                "-c",
                (
                    "import urllib.request,sys; "
                    "urllib.request.urlopen("
                    f"'http://127.0.0.1:{remote_setup_port}/setup.sh', timeout=3"
                    ")"
                ),
            ],
            "interval": "5s",
            "timeout": "3s",
            "retries": 5,
            "start_period": "5s",
        },
    }

    services: dict[str, Any] = {}
    if llm_server_enabled:
        services["llm-server"] = service
    services["omniroute"] = omniroute_service
    services["remote-setup"] = remote_setup_service
    document = {
        "services": services,
        "volumes": {"omniroute-data": {}, "remote-setup-data": {}},
    }
    return HEADER_COMMENT + yaml.safe_dump(
        document, sort_keys=False, default_flow_style=False
    )


def write_compose(
    cfg: dict[str, Any],
    *,
    models_dir: str,
    presets_path: str,
    repo_root: str,
    omni_router_master_key: str = "",
    path: Path,
) -> None:
    """Publish the compose document atomically and never world-readable.

    The rendered YAML carries OMNI_ROUTER_MASTER_KEY, the OmniRoute
    dashboard password and the llm-server API key, so it must never exist
    on disk with a permissive mode -- not even for the instant between
    `write_text()` and a follow-up `chmod()` under the usual 022 umask.
    Write into a private temp file in the destination directory, chmod it
    to 0600 *before* any secret reaches it, fsync it, then os.replace()
    it into place: a reader (podman-compose mid-read) sees either the
    complete old file or the complete new one, never a truncated mix, and
    a failure anywhere leaves any pre-existing file untouched.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    content = render_compose(
        cfg,
        models_dir=models_dir,
        presets_path=presets_path,
        repo_root=repo_root,
        omni_router_master_key=omni_router_master_key,
    )
    fd, tmp_name = tempfile.mkstemp(
        dir=str(path.parent), prefix=".docker-compose.", suffix=".tmp"
    )
    try:
        os.chmod(tmp_name, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_name, path)
    except BaseException:
        Path(tmp_name).unlink(missing_ok=True)
        raise
