"""Render llama-server router presets.ini from models.yml.

Uses configparser so the output is always syntactically valid. No [DEFAULT] section
and no top-level keys are emitted, because llama-server treats every section as a
model preset and would register a phantom model.

Format reference: llama.cpp tools/server/README.md
"""

from __future__ import annotations

import configparser
import io
from pathlib import Path
from typing import Any

from pylib.config import enabled_models

# llama-server parses every section as a model preset, including [DEFAULT] and any
# bare top-level keys. Emitting `version = 1` therefore registers a phantom model
# named "DEFAULT"/"default", verified against ghcr.io/ggml-org/llama.cpp:server-vulkan.
# The file must contain nothing but the [*] globals and one section per enabled model.
HEADER_COMMENT = "; Generated by llm-env. Do not edit; regenerated on every start.\n"


def render_presets(cfg: dict[str, Any], models_dir: str, device: str) -> str:
    runtime = cfg.get("runtime", {})

    parser = configparser.ConfigParser()
    parser.optionxform = str  # preserve hyphenated keys verbatim

    parser["*"] = {
        "device": device,
        "parallel": str(runtime["parallel_slots"]),
        "ubatch-size": str(runtime["ubatch_size"]),
        "flash-attn": "on" if runtime["flash_attn"] else "off",
        "cache-type-k": str(runtime["cache_type_k"]),
        "cache-type-v": str(runtime["cache_type_v"]),
        "fit": "off",
        "context-shift": "off",
    }

    for model in enabled_models(cfg):
        parser[model["alias"]] = {
            "model": str(Path(models_dir) / model["file"]),
            "ctx-size": str(model["ctx_size"]),
            "n-gpu-layers": str(model["n_gpu_layers"]),
        }

    buffer = io.StringIO()
    parser.write(buffer)
    return HEADER_COMMENT + buffer.getvalue()


def write_presets(
    cfg: dict[str, Any], models_dir: str, device: str, path: Path
) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_presets(cfg, models_dir, device), encoding="utf-8")
